version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password
      POSTGRES_DB: images_db
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: postgres_data
